"""
doc_generator.py — Permit Application Document Generator

Generates a professional DOCX permit application package based on
pipeline analysis results. The document is structured to align with
FilmLA submission requirements.
"""

from __future__ import annotations

import io
from datetime import datetime, timedelta

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT

from app.schemas import PipelineResult, ScriptResult


def _add_heading_styled(doc, text, level=1):
    """Add a heading with FilmLA-inspired styling."""
    heading = doc.add_heading(text, level=level)
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0, 0x9C, 0xDE)  # FilmLA cyan
    return heading


def _add_table_row(table, cells_data, bold_first=True):
    """Add a row to a table with optional bold first cell."""
    row = table.add_row()
    for i, data in enumerate(cells_data):
        cell = row.cells[i]
        cell.text = str(data)
        for paragraph in cell.paragraphs:
            paragraph.style.font.size = Pt(10)
            if i == 0 and bold_first:
                for run in paragraph.runs:
                    run.bold = True


def _set_cell_shading(cell, color_hex):
    """Set background color for a table cell."""
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), color_hex)
    shading.set(qn("w:val"), "clear")
    cell._tc.get_or_add_tcPr().append(shading)


def generate_single_scene_doc(result: PipelineResult) -> io.BytesIO:
    """Generate a permit application document for a single scene."""
    doc = Document()

    # --- Styles ---
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    # === COVER PAGE ===
    doc.add_paragraph("")
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("FILM PERMIT APPLICATION PACKAGE")
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0, 0x9C, 0xDE)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Generated by PermitAgent")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)

    doc.add_paragraph("")

    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    today = datetime.now()
    run = info.add_run(f"Date: {today.strftime('%B %d, %Y')}")
    run.font.size = Pt(11)

    ref = doc.add_paragraph()
    ref.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = ref.add_run(f"Reference: {result.breakdown.scene_id}")
    run.font.size = Pt(11)

    doc.add_page_break()

    # === SECTION 1: PRODUCTION INFORMATION ===
    _add_heading_styled(doc, "1. Production Information", level=1)

    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    header = table.rows[0]
    header.cells[0].text = "Field"
    header.cells[1].text = "Details"
    for cell in header.cells:
        _set_cell_shading(cell, "202535")
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.bold = True

    fields = [
        ("Production Company", "[TO BE COMPLETED]"),
        ("Production Title", "[TO BE COMPLETED]"),
        ("Producer / Contact", "[TO BE COMPLETED]"),
        ("Phone", "[TO BE COMPLETED]"),
        ("Email", "[TO BE COMPLETED]"),
        ("Filming Date(s)", "[TO BE COMPLETED]"),
        ("Filming Hours", "[TO BE COMPLETED]"),
        ("Scene Reference", result.breakdown.scene_id),
        ("Permit Type", "FilmLA Master Permit"),
    ]
    for label, value in fields:
        _add_table_row(table, [label, value])

    doc.add_paragraph("")

    # === SECTION 2: LOCATION DETAILS ===
    _add_heading_styled(doc, "2. Location Details", level=1)

    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    header = table.rows[0]
    header.cells[0].text = "Field"
    header.cells[1].text = "Details"
    for cell in header.cells:
        _set_cell_shading(cell, "202535")
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.bold = True

    env = result.environment
    loc_fields = [
        ("Filming Location", result.scene_input.location or "[TO BE COMPLETED]"),
        ("Environment Type", env.environment_type.value.upper()),
        ("Public / Private", env.public_or_private.upper()),
        ("Jurisdiction", env.jurisdiction),
        ("Sub-Zone / District", env.sub_zone or "N/A"),
        ("Noise Restrictions Apply", "YES" if env.noise_restrictions else "NO"),
        ("Interior / Exterior", result.breakdown.interior_exterior),
        ("Time of Day", result.breakdown.time_of_day),
    ]
    for label, value in loc_fields:
        _add_table_row(table, [label, value])

    if env.nearby_sensitive_sites:
        doc.add_paragraph("")
        doc.add_heading("Nearby Sensitive Sites (within 1000 ft)", level=3)
        for site in env.nearby_sensitive_sites:
            doc.add_paragraph(site, style="List Bullet")

    doc.add_paragraph("")

    # === SECTION 3: ACTIVITY DESCRIPTION ===
    _add_heading_styled(doc, "3. Activity Description", level=1)

    doc.add_heading("Permit Description", level=3)
    doc.add_paragraph(result.compliance_plan.permit_description)

    doc.add_heading("Scene Summary", level=3)
    doc.add_paragraph(result.breakdown.summary)

    if result.scene_input.notes:
        doc.add_heading("Production Notes", level=3)
        doc.add_paragraph(result.scene_input.notes)

    # Production elements
    doc.add_heading("Production Elements", level=3)
    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    header = table.rows[0]
    header.cells[0].text = "Element"
    header.cells[1].text = "Details"
    for cell in header.cells:
        _set_cell_shading(cell, "202535")
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.bold = True

    b = result.breakdown
    _add_table_row(table, ["Cast / Characters", ", ".join(b.characters) if b.characters else "See script breakdown"])
    _add_table_row(table, ["Background Performers", str(b.crowd_size_estimate)])
    _add_table_row(table, ["Props", ", ".join(b.props) if b.props else "None"])
    _add_table_row(table, ["Vehicles", ", ".join(b.vehicles) if b.vehicles else "None"])
    _add_table_row(table, ["Special Effects", ", ".join(b.special_effects) if b.special_effects else "None"])

    doc.add_paragraph("")

    # === SECTION 4: REPORTABLE ELEMENTS ===
    if result.exposures.exposures:
        _add_heading_styled(doc, "4. Reportable Elements & Special Activities", level=1)

        doc.add_paragraph(
            f"Overall Risk Assessment: {result.exposures.overall_risk.value.upper()}"
        )

        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        header = table.rows[0]
        for i, h in enumerate(["Element", "Category", "Risk Level", "Notification Required"]):
            header.cells[i].text = h
            _set_cell_shading(header.cells[i], "202535")
            for p in header.cells[i].paragraphs:
                for run in p.runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.bold = True

        for e in result.exposures.exposures:
            _add_table_row(table, [
                e.element,
                e.category,
                e.risk_level.value.upper(),
                ", ".join(e.requires_notification),
            ], bold_first=False)

        doc.add_paragraph("")

    # === SECTION 5: APPLICABLE REGULATIONS ===
    _add_heading_styled(doc, "5. Applicable Regulations", level=1)

    for r in result.rules.matched_rules:
        p = doc.add_paragraph()
        run = p.add_run(f"[{r.rule_id}] ")
        run.bold = True
        run.font.color.rgb = RGBColor(0, 0x9C, 0xDE)
        run = p.add_run(f"{r.source}")
        run.italic = True
        doc.add_paragraph(r.summary)
        mandatory_text = "MANDATORY" if r.mandatory else "ADVISORY"
        p2 = doc.add_paragraph(f"Compliance: {mandatory_text}")
        if r.applies_to:
            p2.add_run(f"  |  Applies to: {', '.join(r.applies_to)}")
        doc.add_paragraph("")

    # === SECTION 6: REQUIRED PERMITS & NOTIFICATIONS ===
    _add_heading_styled(doc, "6. Required Permits & Notifications", level=1)

    doc.add_heading("Permits to Obtain", level=3)
    for p in result.compliance_plan.required_permits:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(p)

    doc.add_heading("Agencies to Notify", level=3)
    for n in result.compliance_plan.required_notifications:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(n)

    doc.add_heading("Insurance Requirements", level=3)
    for ins in result.compliance_plan.insurance_requirements:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(ins)

    if result.compliance_plan.conditions:
        doc.add_heading("Special Conditions", level=3)
        for c in result.compliance_plan.conditions:
            doc.add_paragraph(c, style="List Bullet")

    doc.add_paragraph("")
    lead = doc.add_paragraph()
    run = lead.add_run(f"Estimated Lead Time: {result.compliance_plan.estimated_lead_time_days} business days")
    run.bold = True
    run.font.size = Pt(12)

    doc.add_paragraph("")

    # === SECTION 7: RISK SIMULATION ===
    _add_heading_styled(doc, "7. Compliance Risk Assessment", level=1)

    feas = result.simulation.overall_feasibility
    doc.add_paragraph(f"Overall Feasibility Score: {feas:.0%}")
    doc.add_paragraph(f"Recommendation: {result.simulation.recommendation}")

    if result.simulation.scenarios:
        doc.add_heading("Risk Scenarios", level=3)
        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        header = table.rows[0]
        for i, h in enumerate(["Scenario", "Probability", "Impact", "Mitigation"]):
            header.cells[i].text = h
            _set_cell_shading(header.cells[i], "202535")
            for p in header.cells[i].paragraphs:
                for run in p.runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.bold = True

        for s in result.simulation.scenarios:
            _add_table_row(table, [
                s.scenario_name,
                f"{s.probability:.0%}",
                s.impact.value.upper(),
                s.mitigation,
            ], bold_first=False)

    doc.add_paragraph("")

    # === SECTION 8: SUBMISSION CHECKLIST ===
    _add_heading_styled(doc, "8. Submission Checklist", level=1)

    checklist = [
        "Completed FilmLA permit application (online at filmla.com)",
        "Certificate of Insurance naming City of Los Angeles as additional insured",
        "Location agreement / property owner consent (if private property)",
        "Traffic control plan (if lane closures required)",
        "Neighborhood notification flyers (500 ft radius, 24-72 hrs advance)",
    ]

    # Add dynamic items based on exposures
    for e in result.exposures.exposures:
        if e.category == "equipment" and "drone" in e.element.lower():
            checklist.append("FAA Part 107 Remote Pilot Certificate (copy)")
            checklist.append("FAA airspace authorization (LAANC or waiver)")
            checklist.append("FilmLA Drone Supplemental form")
        if e.category == "weapons":
            checklist.append("FilmLA Weapons Supplemental form")
            checklist.append("LAPD notification confirmation")
            checklist.append("Licensed armorer credentials")
        if e.category == "pyrotechnics":
            checklist.append("FilmLA Pyrotechnics Supplemental form")
            checklist.append("CA State Fire Marshal pyrotechnician license (copy)")
            checklist.append("LAFD fire safety plan")

    # Deduplicate
    seen = set()
    unique_checklist = []
    for item in checklist:
        if item not in seen:
            unique_checklist.append(item)
            seen.add(item)

    for item in unique_checklist:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(item)

    doc.add_paragraph("")

    # === FOOTER ===
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("— Document generated by PermitAgent —")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)
    run.italic = True

    footer2 = doc.add_paragraph()
    footer2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer2.add_run(f"Generated: {today.strftime('%Y-%m-%d %H:%M')}  |  This is a system-generated document. Verify all information before submission.")
    run.font.size = Pt(7)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer


def generate_script_doc(script_result: ScriptResult) -> io.BytesIO:
    """Generate a comprehensive permit package for a full script."""
    doc = Document()

    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10)

    today = datetime.now()

    # === COVER PAGE ===
    doc.add_paragraph("")
    doc.add_paragraph("")
    title = doc.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title.add_run("COMPREHENSIVE FILM PERMIT\nAPPLICATION PACKAGE")
    run.bold = True
    run.font.size = Pt(24)
    run.font.color.rgb = RGBColor(0, 0x9C, 0xDE)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Full Script Compliance Analysis")
    run.font.size = Pt(14)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)

    doc.add_paragraph("")
    info = doc.add_paragraph()
    info.alignment = WD_ALIGN_PARAGRAPH.CENTER
    info.add_run(f"Date: {today.strftime('%B %d, %Y')}\n").font.size = Pt(11)
    info.add_run(f"Scenes: {script_result.summary.total_scenes}\n").font.size = Pt(11)
    info.add_run(f"Feasibility: {script_result.summary.average_feasibility:.0%}").font.size = Pt(11)

    doc.add_page_break()

    # === EXECUTIVE SUMMARY ===
    _add_heading_styled(doc, "Executive Summary", level=1)

    sm = script_result.summary
    doc.add_paragraph(sm.overall_recommendation)

    table = doc.add_table(rows=1, cols=2)
    table.style = "Table Grid"
    header = table.rows[0]
    header.cells[0].text = "Metric"
    header.cells[1].text = "Value"
    for cell in header.cells:
        _set_cell_shading(cell, "202535")
        for p in cell.paragraphs:
            for run in p.runs:
                run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                run.bold = True

    _add_table_row(table, ["Total Scenes", str(sm.total_scenes)])
    _add_table_row(table, ["Total Reportable Exposures", str(sm.total_exposures)])
    _add_table_row(table, ["Total Rules Matched", str(sm.total_rules_matched)])
    _add_table_row(table, ["Unique Permits Required", str(len(sm.unique_permits_required))])
    _add_table_row(table, ["Highest Risk Level", sm.highest_risk.value.upper()])
    _add_table_row(table, ["Average Feasibility", f"{sm.average_feasibility:.0%}"])
    _add_table_row(table, ["Maximum Lead Time", f"{sm.max_lead_time_days} business days"])
    _add_table_row(table, ["High-Risk Scenes", str(len(sm.high_risk_scenes))])

    doc.add_paragraph("")

    # === ALL PERMITS REQUIRED ===
    _add_heading_styled(doc, "Required Permits — All Scenes", level=1)
    for p in sm.unique_permits_required:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(p)

    doc.add_heading("Required Notifications", level=3)
    for n in sm.unique_notifications:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(n)

    doc.add_heading("Insurance Requirements", level=3)
    for ins in sm.unique_insurance:
        para = doc.add_paragraph(style="List Bullet")
        run = para.add_run("☐  ")
        run.font.size = Pt(12)
        para.add_run(ins)

    doc.add_page_break()

    # === SCENE-BY-SCENE ANALYSIS ===
    _add_heading_styled(doc, "Scene-by-Scene Analysis", level=1)

    for i, sr in enumerate(script_result.scene_results):
        ps = script_result.parsed_scenes[i]

        doc.add_heading(f"Scene {ps.scene_number}: {ps.slug_line}", level=2)

        # Scene info table
        table = doc.add_table(rows=1, cols=2)
        table.style = "Table Grid"
        header = table.rows[0]
        header.cells[0].text = "Field"
        header.cells[1].text = "Details"
        for cell in header.cells:
            _set_cell_shading(cell, "3f4a6a")
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
                    run.bold = True

        _add_table_row(table, ["Time of Day", sr.breakdown.time_of_day])
        _add_table_row(table, ["INT / EXT", sr.breakdown.interior_exterior])
        _add_table_row(table, ["Setting", sr.breakdown.setting_description])
        _add_table_row(table, ["Location", sr.scene_input.location or ps.location_hint])
        _add_table_row(table, ["Environment", sr.environment.environment_type.value.upper()])
        _add_table_row(table, ["Jurisdiction", sr.environment.jurisdiction])
        _add_table_row(table, ["Crowd Size", str(sr.breakdown.crowd_size_estimate)])
        _add_table_row(table, ["Risk Level", sr.exposures.overall_risk.value.upper()])
        _add_table_row(table, ["Feasibility", f"{sr.simulation.overall_feasibility:.0%}"])

        doc.add_paragraph("")

        # Exposures
        if sr.exposures.exposures:
            doc.add_heading("Reportable Elements", level=4)
            for e in sr.exposures.exposures:
                doc.add_paragraph(
                    f"• {e.element} ({e.category}, {e.risk_level.value.upper()}) — {e.description}"
                )

        # Permits for this scene
        doc.add_heading("Permits Required", level=4)
        for p in sr.compliance_plan.required_permits:
            doc.add_paragraph(f"• {p}")

        # Permit description
        doc.add_heading("Permit Application Text", level=4)
        doc.add_paragraph(sr.compliance_plan.permit_description)

        if i < len(script_result.scene_results) - 1:
            doc.add_paragraph("")
            doc.add_paragraph("―" * 40)
            doc.add_paragraph("")

    doc.add_page_break()

    # === SUBMISSION CHECKLIST ===
    _add_heading_styled(doc, "Master Submission Checklist", level=1)

    checklist = [
        "Completed FilmLA permit application (online at filmla.com)",
        "Certificate of Insurance — $1M general liability, $2M aggregate",
        "Certificate of Insurance — City of LA named as additional insured",
        "Workers' compensation certificate",
        "Location agreement(s) / property owner consent",
        "Neighborhood notification plan (500 ft radius)",
        "Notification flyers prepared (24-72 hrs advance delivery)",
    ]

    # Add scene-specific items
    all_categories = set()
    for sr in script_result.scene_results:
        for e in sr.exposures.exposures:
            all_categories.add(e.category)

    if "equipment" in all_categories:
        checklist.extend([
            "FAA Part 107 Remote Pilot Certificate (copy)",
            "FAA airspace authorization (LAANC or waiver)",
            "FilmLA Drone Supplemental form",
            "Aircraft liability insurance — $5M minimum",
        ])
    if "weapons" in all_categories:
        checklist.extend([
            "FilmLA Weapons Supplemental form",
            "LAPD notification — 24 hrs advance",
            "Licensed armorer credentials",
            "Safety briefing plan for cast and crew",
        ])
    if "pyrotechnics" in all_categories:
        checklist.extend([
            "FilmLA Pyrotechnics Supplemental form",
            "CA State Fire Marshal pyrotechnician license",
            "LAFD fire safety plan",
            "Fire suppression equipment on set",
        ])
    if "vehicles" in all_categories:
        checklist.extend([
            "LADOT traffic control plan",
            "Parking restriction signs (post 24 hrs advance)",
        ])
    if "crowd" in all_categories:
        checklist.extend([
            "Crowd management plan",
        ])

    seen = set()
    for item in checklist:
        if item not in seen:
            para = doc.add_paragraph(style="List Bullet")
            run = para.add_run("☐  ")
            run.font.size = Pt(12)
            para.add_run(item)
            seen.add(item)

    # Footer
    doc.add_paragraph("")
    doc.add_paragraph("")
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run("— Document generated by PermitAgent —")
    run.font.size = Pt(8)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)
    run.italic = True

    footer2 = doc.add_paragraph()
    footer2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer2.add_run(f"Generated: {today.strftime('%Y-%m-%d %H:%M')}  |  Verify all information before submission to FilmLA.")
    run.font.size = Pt(7)
    run.font.color.rgb = RGBColor(0x9F, 0xA4, 0xB4)

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    return buffer
